### ISSUE TITLE
Send filter stderr to error log

### ISSUE THREAD

**Issue by q3cpma** [msharov/snownews#31]
Hello,

if opening snownews with a `~/.snownews/urls` file containing only `exec:curl -s https://packages.gentoo.org/packages/added.atom|||xsltproc /usr/share/snownews/filters/xsltproc/atom2rss -` then refreshing, I get some intermittent errors like these (don't know if these belong to snownews or xsltproc):

https://my.mixtape.moe/mnawxc.png

This is using 1.6.10, any idea?

**Comment by kouya** [comment]
These probably come from xsltproc. The stderr is most likely from the filter, snownews doesn't print any libxml parsing errors to the screen if I remember.

I think the correct fix is to pipe stderr from the filter to oblivion.

I am not sure I would want all filter error output to disappear as users would be confused as to why a filter doesn't work. Probably should go to the error log instead.
