### ISSUE TITLE
EndTag not found when parsing Atom feed

### ISSUE THREAD

**Issue by Strahinja** [msharov/snownews#50]
I'm trying to parse [suckless.org Atom feed][1], but I'm getting the following error:
```
I/O error : write error
Entity: line 56: parser error : EndTag: '</' not found
<rdf:li rdf:resource="https://www.suckless.org/#2012-10-14T00:00Z"/>
```
I'm using the `atom2rss` script from `contrib/filters/xsltproc/atom2rss` from the repo, which I copied to `~/.local/bin` and added the feed using the
```
exec:curl https://suckless.org/atom.xml
```
and
```
xsltproc /home/[username]/.local/bin/atom2rss -
```

[1]: https://suckless.org/atom.xml

**Comment by msharov** [comment]
Commit de3bd8b28191c4d4bc1be18275786613bcbc0c94 replaces the atom2rss filter script with native support for reading Atom feeds. I have verified that the suckless feed loads correctly.
