### ISSUE TITLE
Transfer request

### ISSUE THREAD

**Issue by msharov** [msharov/snownews#54]
You state in commit a243e2b517c407a5464237b0045a7ea327b90a50 that you no longer wish to maintain the project. I'm willing to take over the maintenance. I have the time and I use it frequently myself.

If you transfer ownership to me (under github project settings) I'd be able to keep the issues and PRs and restart development where you left off.

**Comment by kouya** [comment]
Hiya. I would prefer to keep the project as my archive and not breaking links. If you just fork it on github I will link to there stating development continues in another repository and close all issues sending them there as well. Some of them are most likely so outdated they are irrelevant now.

**Comment by msharov** [comment]
Changing links over is one big advantage of doing a transfer. Github promises to rewrite all the links to point to the new repository, and that is where they ought to point. For the users, so they would know where active development is taking place; for me, so my work on the new repository does not remain unnoticed by them; and for you, so you would not be continually bothered by change requests you don't have time to work on.

A Github repository is mainly the community content of the project; the links, the issues, PRs, and the history of these, all created by the users. These are the things you don't want on an archived project and are proposing to just throw away. This is inconsiderate to the users who created them, and misleading, keeping up their hopes that the issues they filed would be addressed.

Now, I can understand you wanting to keep it as an archive, but there are better ways of doing so. The easiest would be to simply fork back from my repository, which would automatically point to it as the currently developed one. Another would be to recreate it after transfer, as a new clean repository, push into it and explicitly archive it (under settings, same place as the transfer). This way you would keep the code, the glory, or whatever :)

Then I would get the community content that you don't want anyway, and the users will get notified when I fix the problems they reported. I really do strongly recommend doing it this way.

**Comment by kouya** [comment]
Well yeah, the logic is sound to keep the issues and all intact if you really want to keep them. I can transfer it over then.

**Comment by msharov** [comment]
Thanks! :) The transfer appears successful. I should be able to get in a few fixes today.

**Comment by msharov** [comment]
I also see that the transfer created an automatic redirect from https://github.com/kouya/snownews to this repository. When you recreate yours for archival purposes it might be a good idea to pick a different name to keep the redirect in place. snownews-orig?

**Comment by kouya** [comment]
Hm, I guess it's fine that it redirects then. I will leave it like that.
