### ISSUE TITLE
snownews 1.8 OSX build failure

### ISSUE THREAD

**Issue by chenrui333** [msharov/snownews#59]
Trying to build snownews 1.8, but run into some build failure.

```
==> make install
Last 15 lines from /Users/rchen/Library/Logs/Homebrew/snownews/02.make:
uiutil.c:279:5: error: unknown type name 'cchar_t'; did you mean 'wchar_t'?
    cchar_t ch = {};
    ^~~~~~~
    wchar_t
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_wchar_t.h:34:26: note: 'wchar_t' declared here
typedef __darwin_wchar_t wchar_t;
                         ^
uiutil.c:279:18: error: scalar initializer cannot be empty
    cchar_t ch = {};
                 ^~
2 errors generated.
```

After updating it 

```diff
-    cchar_t ch = {};
+    wchar_t ch = 0;
```

I cannot use the app properly

```
$ /usr/local/Cellar/snownews/1.8/bin/snownews
Exiting via signal 11.
Aborting program execution!
An internal error occured. Snownews has quit, no changes has been saved!
Please submit a bugreport at https://github.com/msharov/snownews/issues
----
While executing: (null)
Error as reported by the system: Signal
```

---

relates to Homebrew/homebrew-core#77055

**Comment by aabacchus** [comment]
I've got this error too. I'm confused, because there's nothing wrong with my `/usr/include/ncurses.h`, and I can make a test program which `include`s `<ncurses.h>`, and `cchar_t` is fine. A temporary workaround is to paste the definition of the struct type into the top of `uiutil.c`, directly taken from `ncurses.h`:

```c
#define CCHARW_MAX      5
typedef struct
{
    attr_t      attr;
    wchar_t     chars[CCHARW_MAX];
    int         ext_color;      /* color pair, must be more than 16-bits */
}
cchar_t;
```

Anyway, it's very confusing that *that* in particular isn't recognised, since the rest of `ncurses.h` is pretty vital (try commenting out the include).

**Comment by msharov** [comment]
Then you should do `cpp -E uiutil.c` and look for cchar_t in there. If it isn't, then your ncurses does not support widechars. If it is, then you shouldn't have build errors.

**Comment by aabacchus** [comment]
`cpp -E uiutil.c` includes `/usr/include/ncurses.h`, which contains the definition for cchar_t in it as expected. However, I do have a build error, but 448f9e2 fixes it; I suppose `NCURSES_WIDECHAR` isn't defined in my `ncurses.h`?

**Comment by msharov** [comment]
`NCURSES_WIDECHAR` is defined in `ncurses.h` on line 203, conditional on `_XOPEN_SOURCE >= 500`. This appears to be yet another instance of a platform annoyingly hiding stuff until some magic constant is defined. Setting `_GNU_SOURCE` should have enabled it. It usually is the right way to say "give me everything". But I guess in this case there is some other password required. I don't think I'm supposed to define `_XOPEN_SOURCE` directly.

**Comment by aabacchus** [comment]
I'm using the musl libc, could this be why?

**Comment by msharov** [comment]
According to [musl manual](http://musl.libc.org/doc/1.1.24/manual.html), the `_GNU_SOURCE` macro should have enabled `_XOPEN_SOURCE` at level 700. Even the default `_BSD_SOURCE` should have done it. So the problem must be elsewhere.

**Comment by aabacchus** [comment]
I think `_GNU_SOURCE` disables `_XOPEN_SOURCE`:
from musl's `features.h`:
```c
#if defined(_ALL_SOURCE) && !defined(_GNU_SOURCE)
#define _GNU_SOURCE 1
#endif

...

#if !defined(_POSIX_SOURCE) && !defined(_POSIX_C_SOURCE) \
 && !defined(_XOPEN_SOURCE) && !defined(_GNU_SOURCE) \
 && !defined(_BSD_SOURCE) && !defined(__STRICT_ANSI__)
#define _BSD_SOURCE 1
#define _XOPEN_SOURCE 700
#endif
```
`_GNU_SOURCE` is set in `config.h` before `features.h` is included (via stdio.h), so this prevents `_XOPEN_SOURCE` from being defined, which in turn prevents `NCURSES_WIDECHAR`. So, compiling `uiutil.c` but not defining `_GNU_SOURCE` in config.h works, but then none of the other files will compile. I'm not a C programmer, and this is confusing.

Compare to glibc's `features.h`:
```c
#ifdef _GNU_SOURCE
...
#undef _XOPEN_SOURCE
#define _XOPEN_SOURCE 700
...
#endif
```

**Comment by msharov** [comment]
I would say that this is a MUSL bug. In its manual it explicitly states that `_GNU_SOURCE` enables the features of all the other macros, so they need to fix their headers to do just that.

**Comment by aabacchus** [comment]
I've talked to some people from musl, and they've explained the following:
`_GNU_SOURCE` doesn't `#define` the other macros, but it enables the same features as all the other macros. So, it is a bug in *ncurses* which only `#ifdef`s `_XOPEN_SOURCE`, when `_GNU_SOURCE` should also enable the WIDECHAR stuff.

The quickfix is to define `_XOPEN_SOURCE 700` as well as `_GNU_SOURCE` in config.h.

They suggested switching to [netbsd-curses](https://github.com/sabotage-linux/netbsd-curses), which has all the standard curses api and is much lighter.
