### ISSUE TITLE
Deprecated SPDX license identifiers

### ISSUE THREAD

**Issue by chenrui333** [msharov/snownews#66]
👋  [GPL-3.0](https://spdx.org/licenses/GPL-3.0.html) is a deprecated SDPX license identifier, it would be preferred to use [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html) (see [here](https://spdx.org/licenses/) for details).

cc @msharov

relates to https://github.com/Homebrew/homebrew-core/pull/77055

**Comment by msharov** [comment]
I do not use SDPX identifiers anywhere. If you are referring to the license identifier on the main github page, I have no control over that; github scans the LICENSE.md file to determine it. To specify the snownews license as GPL-3.0-only, github would have to scan the copyright headers of some of the source files, where "or later" clause is missing. I suggest you refer this issue to the github license scanning project.
