### ISSUE TITLE
Add html2atom to filters/

### ISSUE THREAD

**Issue by sjehuda** [msharov/snownews#67]
_"html2atom is a script that allows to form a custom Atom Syndication feed, in essence, this program is intended for use with websites that neither provide Atom nor RSS feeds"._

https://github.com/sjehuda/html2atom

**Comment by msharov** [comment]
Your script does not do what you claim. It is written specifically to get a feed of releases for a particular project html page. This is not generally useful.

Also, while snownews used to own and publish user-submitted filter scripts, this is now deprecated. The existing filter in the docs dir is only intended as an example. It is not installed with snownews and may be removed in the future.
