### ISSUE TITLE
Remove HTML transformation section from README

### ISSUE THREAD

**Issue by BioBox** [msharov/snownews#72]
There's a section in the README about influencing the behavior of HTML reading, but grepping the source for mentions of that filename turn up nothing. I looked through the commit history and found that it was removed: 5792d4aebdd5c21dcd72c0b445c1c218d3ab0a05.

Can someone remove that from the README please? I'm brand new to this software so I don't feel qualified to do this myself.

**Comment by msharov** [comment]
Fixed by 3868284abbbbb362056676b51449a58b7d0f1f37
