### ISSUE TITLE
Smartfeeds should sort items by date

### ISSUE THREAD

**Issue by Djamoussa** [msharov/snownews#74]
Hi

I didn't find the way to sort feeds by date in "New headlines" feed.
Actually, there are sort by date BUT inside there own feed

Did i miss something ?
Is it possible to add this features  ?

**Comment by msharov** [comment]
smartfeeds pull unread items from all the feeds in order, with no sorting. Yes, it would be the right thing to do to add them sorted by date.

**Comment by Hamburgefonts** [comment]
i agree. it would be super cool to have items sorted by date when opening a feed – with the most resent post on top.

**Comment by msharov** [comment]
Implemented by 9e7e7c829140920d58d39c07525d95e2902c256f.
