### ISSUE TITLE
mpv

### ISSUE THREAD

**Issue by slackjeff** [msharov/snownews#75]
is there a possibility to use mpv to play youtube videos?

**Comment by msharov** [comment]
Huh? Snownews is an RSS reader, it has nothing to do with youtube or videos. The only content action it can take is to launch a browser to go to the link in an RSS entry. It is the browser that will be displaying that content, including playing videos, so all you have to do is configure the browser to do so. And no, I don't know how to get elinks to play youtube videos with mpv.
