### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by b3noist** [msharov/snownews#77]
After a recent reboot, I tried to start snownews as normal and only got this error message:
```
Exiting via signal Segmentation fault.
Aborting program execution!
An internal error occured. Snownews has quit, no changes has been saved!
Please submit a bugreport at https://github.com/msharov/snownews/issues
----
While executing: MainSignalHandler
Error as reported by the system: Signal
```

A couple of reboots and reinstalling snownews from the AUR did not fix the issue.

Distro: Arch
WM: Sway
Kernel: 5.16.14-arch1-1

**Comment by b3noist** [comment]
D'oh! Got a little bit ahead of myself in making this issue.

I deleted ~/.config/snownews and it started working again.

Apologies for the spurious issue.

**Comment by b3noist** [comment]
Just to supplement this, I copied the urls.opml out of ~/.config/snownews and recopied it in, and it started segfaulting again. When I removed it again, it was able to start up properly once more. I manually re-entered my URLs and restarted snownews to confirm that it still works, and it does. I didn't realise until now that snownews wrote to the config on exiting, but I think I see now what might have happened.

When I rebooted, I didn't shut down anything, so presumably snownews was simply forced to quit by systemd before it could successfully write to the configs, resulting in something being screwed up enough to halt things at initialisation. I'm not sure what this suggests, but maybe it could be of value to know?

**Comment by msharov** [comment]
OPML parsing is at the end of parse.c, it's only 40 lines of code, and there aren't that many places to segfault. I'd need to have a test case to find the problem, so if you can get a urls.opml that reliably causes a crash, please attach it here.
