### ISSUE TITLE
Modify installation to install contrib scripts

### ISSUE THREAD

**Issue by kozross** [msharov/snownews#9]
Given that we've now taken 'ownership' of those, it would make sense for them to be part of the installation. This needs to also be documented appropriately.

**Comment by msharov** [comment]
Having reviewed the contrib scripts, I do not see the utility of including them with snownews at all. The ones in the untested/ subdir are just cosmetic fixes to specific feeds, and really don't belong here. The ones in filters/ are useful, such as the Atom-to-rss conversion, but should rather be reimplemented as part of snownews itself.

Therefore, I'm going to deprecate contrib scripts altogether and will at some point remove them.
